### ISSUE TITLE
Francesco's LE filtering

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#15]
Implement the filtering steps described in Giardina et al. _in prep_.:

> We first applied a rainfall filter with a buffer of 6 hours after each rain event to exclude interception evaporation and to avoid sensor saturation with high relative humidity (Li et al., 2019). We removed data with relative humidity higher than the 95% quantile to exclude the impact of dew evaporation on ET (Knauer, Zaehle, et al., 2018). To avoid stable boundary layer conditions, we excluded data where the sensible heat flux was smaller than 5 W m-2 and incoming shortwave radiation was smaller than 50 W m-2. Finally, only daytime data (GPP, ET and VPD > 0) were considered. Half-hourly data were aggregated into daily data to reduce noise and to avoid the ET-VPD hysteresis effect, observed at sub-daily timescales (Q. Zhang et al., 2014). While aggregating to the daily level, the daily mean was calculated for all variables, except for VPD (for which we calculated the daily maximum), ET and precipitation (for which we used the daily sum). We only retained daily estimates with at least 8 measured half-hourly points, as in (Li et al., 2019).

@fgiardin could you please ask @khufkens where to add your code to integrate this into flux_data_kit? A possibility is to create a column in the that identifies whether the data is giardina-filtered or not (binary information)

**Comment by fgiardin** [comment]
Sure thing, I think it's pretty straight forward to do. But do you think it will be useful? This is a very specific filtering used to predict ET. In any case, it will be accessible in the [fET repo](https://github.com/computationales/fET) that I've been preparing for publication (it's a dedicated script [here](https://github.com/computationales/fET/blob/main/analysis/1.data_screening_euler.R)). I'm asking because you were yourself skeptical of the intense filtering I was applying on the data (I found it in the literature in studies that focused on ET/LE). For instance, in your 2018 New Phyt paper you didn't use it to predict LUE.

**Comment by khufkens** [comment]
Won't fix, is inconsistent with original PLUMBER workflow.
