### ISSUE TITLE
Package icoscp not available

### ISSUE THREAD

**Issue by stineb** [computationales/FluxDataKit#33]
```r
 library(FluxDataKit)
source("data-raw/01_collect_meta-data.R")
```
Returns
```r
Error in library(icoscp) : there is no package called ‘icoscp’
```

And the package does not seem to be available from CRAN.
```r
> install.packages("icoscp")
Warning in install.packages :
  package ‘icoscp’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

**Comment by khufkens** [comment]
I never released this to CRAN, because the functionality of the API was shit to begin with.

https://github.com/bluegreen-labs/icoscp

Currently, this has been discontinued because ICOS relies on SPARQL and the package which provides the R interface has been discontinued (I refuse to pick this up). There is now no way to easily query ICOS meta-data via the "established" API. Forward the complaint to ICOS, and lean hard on them (because this is actually quite disgraceful tbh). All respect for the scientific work of Dario et al., but when it comes to managing and directing infrastructure the whole ICOS framework is a disaster (at best).

**Comment by stineb** [comment]
`01_collect_meta-data.R` and `01_setup.Rmd` load the package. Can this be avoided in order to make the code run (given that icoscp is not available (due to SPARQL not being on CRAN)?

**Comment by khufkens** [comment]
Integrated SPARQL into icoscp, added as remote.

https://github.com/bluegreen-labs/icoscp/commit/1c5e76cac435dc6c2c152a135d35177607b839f4
